In [1]:
import tensorflow as tf

#### TensorFlow 张量是不可赋值的也就是常量

In [2]:
#全1张量
x=tf.ones(shape=(2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [4]:
#全0张量
x=tf.zeros(shape=(2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [5]:
#随机张量,从均值为0，标准差为1的正态分布中抽取的随机张量
x=tf.random.normal(shape=(3,1),mean=0.,stddev=1.)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[-0.8949428 ],
       [-0.36773384],
       [ 1.3569177 ]], dtype=float32)>

In [6]:
#随机张量，从0和1之间的均匀分布中抽取的随机张量
x=tf.random.uniform(shape=(3,1),minval=0.,maxval=1.)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.65647495],
       [0.16700172],
       [0.45019913]], dtype=float32)>

#### TensorFlow变量是可变的，tf.Variable是一个类，其作用是管理TensorFlow中的可变状态

In [7]:
v=tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.2763162],
       [ 1.1147283],
       [-1.4382142]], dtype=float32)>

In [8]:
#为TensorFlow变量赋值
v.assign(tf.ones(shape=(3,1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [9]:
#变量+=
v.assign_add(tf.ones(shape=(3,1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[2.],
       [2.],
       [2.]], dtype=float32)>

In [12]:
#变量-=
v.assign_sub(tf.ones(shape=(3,1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.],
       [0.],
       [0.]], dtype=float32)>

#### 张量数学运算

In [13]:
a = tf.ones((2, 2))
b = tf.square(a)  #求平方
print(b)
c = tf.sqrt(a)  #求平方根
print(c)
d = b + c  #两个张量（逐元素）相加
print(d)
e = tf.matmul(a, b)  #计算两个张量的积
print(e)
e *= d  #两个张量（逐元素）相乘
print(e)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


#### GradientTape API

In [14]:
# 检索任意可微表达式相对于其输入的梯度
input_var=tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    result=tf.square(input_var)
gradient=tape.gradient(result,input_var)
gradient